### ISSUE TITLE
please help me understand the file： frozen_inference_graph_face

### ISSUE THREAD

**Issue by lxwithgod** [yeephycho/tensorflow-face-detection#1]
Where find I  frozen_inference_graph_face’s sources file ,please help me,I don't understand the file.

**Comment by yeephycho** [comment]
Follow the README, then you will find a link that can download the *.pb file.

________________________________
发件人: lxwithgod <notifications@github.com>
发送时间: 2017年10月17日 9:17
收件人: yeephycho/tensorflow-face-detection
抄送: Subscribed
主题: [yeephycho/tensorflow-face-detection] please help me understand the file： frozen_inference_graph_face (#1)


Where find I frozen_inference_graph_face’s sources file ,please help me,I don't understand the file.

―

**Comment by lxwithgod** [comment]
I need your mode source code file，i want to know the detail about network,trained process.
thank.
