### ISSUE TITLE
which SSD model you have used to train the model

### ISSUE THREAD

**Issue by deamonDevs** [yeephycho/tensorflow-face-detection#13]
Hey Great work... 
i want to know which SSD model you have used to train the model

**Comment by yeephycho** [comment]
Hi @deamonDevs ,

It is mobilenet SSD.

Yeephycho

**Comment by rafaelbou** [comment]
Hi,
When you say mobilenet, do you mean mobilenet V1  or V2?

Thanks.

**Comment by yeephycho** [comment]
V1

**Comment by rafaelbou** [comment]
Thanks for the quick reply
