### ISSUE TITLE
Unable to stop the stream: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by aolansili** [yeephycho/tensorflow-face-detection#2]
when clone the project, do everything needed and run the do code ,the error "Unable to stop the stream: Inappropriate ioctl for device" outs out,it seems to be worry with cv2.VideoCapture(./media/test.mp4),any advice?

**Comment by yeephycho** [comment]
Sorry to hear that and I suggest you to try other IO library, after all you only need numpy array of the image for the detection.

It also might be related to your OS.

Hope it can work after your modification.

With regards!

**Comment by z362194037** [comment]
@aolansili do you solve the problem? I open the out avi video get error "could not demultiplex stream" It's blank and only 5.7kb
