### ISSUE TITLE
Why frame_num = 1490 ?

### ISSUE THREAD

**Issue by shalabhsingh** [yeephycho/tensorflow-face-detection#20]
Hi, I was going through your source code but couldn't understand why you have used frame_num = 1490 and run through only these many frames in inference_video_face.py file? Can you please clarify it?

**Comment by yeephycho** [comment]
Hi @shalabhsingh,
1490 is my lucky number. You can change with your will.

**Comment by shalabhsingh** [comment]
Hi, my question is why are you limiting the frame numbers? If a video has more than 1490 frames, will it get processed correctly? If yes how? If no, why have you restricted the frame numbers?

**Comment by xiangyann** [comment]
The excess frames will not be processed, 1490 means that only the first minute will be parsed 
1490f/25fps = 59.6 sec
Just assign a large number for whole/long video processing
1 minute is useful for demonstration purposes IMO.
