### ISSUE TITLE
./inference_usbCam_face.py 0 issue

### ISSUE THREAD

**Issue by liupanpan** [yeephycho/tensorflow-face-detection#27]
Hi, when i run ./inference_usbCam_face.py 0, there is a issue as below:
` File "./inference_usbCam_face.py", line 108, in <module>
    (boxes, scores, classes, num_detections) = tDetector.run(image)
  File "./inference_usbCam_face.py", line 73, in run
    feed_dict={image_tensor: image_np_expanded})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1058, in _run
    raise RuntimeError('Attempted to use a closed Session.')
RuntimeError: Attempted to use a closed Session.
`
Could you help me to check the issue?

**Comment by liupanpan** [comment]
luckly, i have fixed the issue.

**Comment by yeephycho** [comment]
Hi @liupanpan ,
Would you please spend a few minutes to share your experience on how did you solved this problem?

With regards!

**Comment by Larnal** [comment]
same issue here... Investigating.
