### ISSUE TITLE
Config needed

### ISSUE THREAD

**Issue by vaishnavm217** [yeephycho/tensorflow-face-detection#3]
Hi,
I am training the same model on WIDERface with the coco default config.
but running ` eval.py` is giving warning for
```
no ground truth in the following classes [1,2]
```
i am using the label map provided by your repo. even went through some of the issues of this problem, still i am getting the same error. Can you post config you used so i can decode this problem?

**Comment by yeephycho** [comment]
I am sorry but I'm currently lack of bandwidth to respond your request.
But I think your request is somehow reasonable, my suggestion for you is to go through the tutorial from google object detection api in tensorflow. I believe that after you finished all the related materials, you are to able to train your customed model. It would take to much time.

Good luck~

**Comment by vaishnavm217** [comment]
Sorry to intrude, I just want to ask did you change the whole config file, like parameters and minimum size or just changed the `PATH_TO_CONFIGURE` ?

**Comment by yeephycho** [comment]
I think I changed necessary part of the config file.

**Comment by taewookim** [comment]
@yeephycho 

In your [face_label_map](https://github.com/yeephycho/tensorflow-face-detection/blob/master/protos/face_label_map.pbtxt), i noticed background as one of the labels. Why was that included? I don't recall seeing that in the TF object detection api tutorial (i.e. the custom pet detector)

**Comment by yeephycho** [comment]
You can ignore the label number or change it to any number you like.
