### ISSUE TITLE
Pipeline config file

### ISSUE THREAD

**Issue by dapladoc** [yeephycho/tensorflow-face-detection#34]
Hi! Could you provide pipeline config file that was used for training, please? It is possible to run this model directly in opencv, but anchors and other parameters should be known to convert the model into opencv format.

**Comment by yeephycho** [comment]
Sorry @dapladoc , but I already lost all the related files so I cannot provide them anymore.
And I think it's a easy task to run the model through opencv.

**Comment by dkurt** [comment]
@dapladoc, @yeephycho, please see https://github.com/opencv/opencv/issues/12075. There is a guide of how we can run the model using OpenCV.

@yeephycho, thank you for your results!
