### ISSUE TITLE
tensorflow-object-detection-api face co-ordinates

### ISSUE THREAD

**Issue by NarenBabuR** [yeephycho/tensorflow-face-detection#38]
**boxes = self.detection_graph.get_tensor_by_name('detection_boxes:0')**  gives me normalized co-ordinates(0.1734, 08956, 0.34567, 012564) of the face detected, but I want un-normlized(original) co-ordinates (245, 475, 300, 600)

**Comment by aqib11** [comment]
I want to crop the faces but i'm also having trouble in getting the face coordinates. Can anyone help?

**Comment by zahra-anvari** [comment]
> **boxes = self.detection_graph.get_tensor_by_name('detection_boxes:0')** gives me normalized co-ordinates(0.1734, 08956, 0.34567, 012564) of the face detected, but I want un-normlized(original) co-ordinates (245, 475, 300, 600)

Hi @NarenBabuR  
Did you find out how to convert normalized coords. to un-normalized? 
Thanks
