### ISSUE TITLE
Need for resizing before evaluating

### ISSUE THREAD

**Issue by bostafh** [yeephycho/tensorflow-face-detection#45]
Hello,
Is the model performing some resizing in the tensorflow back-end ?
I get significantly better result when i crop the outside of an image to make it square. So could it be that the model is resizing images to make them square and by doing so squishing faces ?
Thanks

**Comment by yeephycho** [comment]
Keep the feature of a face will help to get a better detection result.

**Comment by bostafh** [comment]
What does that mean sorry ?
You're not addressing my question, are you ?
You can try by yourself but results are way better on square images than in original aspect ratio.
