### ISSUE TITLE
2 classes defined instead of just one

### ISSUE THREAD

**Issue by eypros** [yeephycho/tensorflow-face-detection#46]
I would like to ask for the 2 classes that you have defined. Is there a specific reason for that?

I have tried to train a one-class with persons and it seemed to me that sometimes multiple classes gives a precision boost for some reason. Is this the case here? Because as far as I can see you don't actually uses the `background` class at all. Are there any background class member that the model could detect for example?

**Comment by yeephycho** [comment]
I don't think so, if you found that a single class doesn't works out, it may because of other issue.
