### ISSUE TITLE
Thanks for your model!

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [yeephycho/tensorflow-face-detection#6]
Hey thanks for training and releasing this model. 
I have incorporated it in Deep Video Analytics / Visual Data Network. 

[1] https://www.deepvideoanalytics.com
[2] https://github.com/VisualDataNetwork/root

**Comment by yeephycho** [comment]
Thanks @AKSHAYUBHAT.
I'll add a link to VDN/root in README so that more people can learn more about Computer Vision.

Regards!
Yours Yeephycho
