### ISSUE TITLE
Convert to tensorflow.js format

### ISSUE THREAD

**Issue by rpolonsky** [yeephycho/tensorflow-face-detection#60]
Is it somehow possible to convert `frozen_inference_graph_face.pb` to tensorflow.js format?

I tried using `tensorflowjs_converter` but can't figure out correct parameters to pass.

That command seems to be wrong:
```
tensorflowjs_converter --input_format=tf_frozen_model --output_node_names='num_detections' --saved_model_tags=serve ./frozen_inference_graph_face.pb  ./result
```

I get an error:
```
ValueError: Unsupported Ops in the model before optimization
NonMaxSuppression
```

If I skip operators check with `--skip_op_check`, then I get an error while trying to use that model:
```
The shape of dict['image_tensor'] provided in model.execute(dict) must be [-1,-1,-1,3], but was [480,640,3]
```

May somebody help me with the correct algorithm to convert that model to tfjs?
Thanks!

**Comment by yeephycho** [comment]
1, It seems that NMS is not supported by tfjs, happy to see that you figured out a way to bypass.
2. Please try [1, 480, 640, 3] as the input shape. tf.expand_dim or numpy api might be helpful.
