### ISSUE TITLE
No output media

### ISSUE THREAD

**Issue by mashrin** [yeephycho/tensorflow-face-detection#7]
Hey, I followed all the instructions but no output media is being created.

Output:
`python inference_video_face.py 
2017-12-29 15:52:24.196885: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-29 15:52:24.196915: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-29 15:52:24.196923: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
inference time cost: 0.417937040329
inference time cost: 0.208209991455
inference time cost: 0.2039539814
inference time cost: 0.204596042633
inference time cost: 0.205924034119
inference time cost: 0.203047990799
inference time cost: 0.202235937119
inference time cost: 0.217959880829
inference time cost: 0.224509954453
inference time cost: 0.210134983063
inference time cost: 0.201905965805
inference time cost: 0.207165956497
inference time cost: 0.202527046204
inference time cost: 0.200993061066
inference time cost: 0.20183300972
inference time cost: 0.202362060547
inference time cost: 0.201920986176
inference time cost: 0.198541164398
inference time cost: 0.209784030914
inference time cost: 0.202893972397
inference time cost: 0.196293830872
inference time cost: 0.201288938522
inference time cost: 0.199282884598
inference time cost: 0.206258058548
inference time cost: 0.20901799202
inference time cost: 0.201825141907
inference time cost: 0.205009222031
inference time cost: 0.202190160751
inference time cost: 0.203970909119
inference time cost: 0.205040216446
inference time cost: 0.208302974701
inference time cost: 0.210053920746
inference time cost: 0.20711684227
inference time cost: 0.211798906326
inference time cost: 0.212251901627
inference time cost: 0.21053814888
inference time cost: 0.210524082184
inference time cost: 0.208800077438
inference time cost: 0.206100940704
inference time cost: 0.214071989059
inference time cost: 0.221938848495
inference time cost: 0.216559886932
inference time cost: 0.221755981445
inference time cost: 0.231920003891
inference time cost: 0.21414899826
inference time cost: 0.213707923889
inference time cost: 0.227074861526
inference time cost: 0.223334789276
inference time cost: 0.242343902588
inference time cost: 0.242468833923
inference time cost: 0.222752094269
inference time cost: 0.216411828995
inference time cost: 0.220861911774
inference time cost: 0.227092027664
inference time cost: 0.220318078995
inference time cost: 0.23770403862
inference time cost: 0.229876041412
inference time cost: 0.219667196274
inference time cost: 0.218620061874
inference time cost: 0.225208044052
inference time cost: 0.213758945465
inference time cost: 0.217224836349
inference time cost: 0.215490102768
inference time cost: 0.214308023453
inference time cost: 0.216567993164
inference time cost: 0.217869997025
inference time cost: 0.21649813652
inference time cost: 0.222114086151
inference time cost: 0.217518091202
inference time cost: 0.209808111191
inference time cost: 0.205770969391
inference time cost: 0.210033178329
inference time cost: 0.21347784996
inference time cost: 0.238358974457
inference time cost: 0.242347002029
inference time cost: 0.264683008194
inference time cost: 0.24779510498
inference time cost: 0.248744010925
inference time cost: 0.250416040421
inference time cost: 0.264840841293
inference time cost: 0.244341135025
inference time cost: 0.246070861816
inference time cost: 0.210253000259
inference time cost: 0.209403038025
inference time cost: 0.211063861847
inference time cost: 0.216904878616
inference time cost: 0.223391056061
inference time cost: 0.235756874084
inference time cost: 0.210615873337
inference time cost: 0.205776929855
inference time cost: 0.221609115601
inference time cost: 0.223328113556
inference time cost: 0.216742992401
inference time cost: 0.221280097961
inference time cost: 0.211334943771
inference time cost: 0.203860998154
inference time cost: 0.203227996826
inference time cost: 0.212304830551
inference time cost: 0.198536872864
inference time cost: 0.202285051346
inference time cost: 0.198318958282
inference time cost: 0.198724985123
inference time cost: 0.210919857025
inference time cost: 0.206523895264
inference time cost: 0.200446128845
inference time cost: 0.209186077118
inference time cost: 0.200613975525
inference time cost: 0.208227872849
inference time cost: 0.20864200592
inference time cost: 0.207768917084
inference time cost: 0.207153081894
inference time cost: 0.21022605896
inference time cost: 0.210891008377
inference time cost: 0.207917928696
inference time cost: 0.202557086945
inference time cost: 0.209172010422
inference time cost: 0.205944061279
inference time cost: 0.201563835144
inference time cost: 0.208555936813
inference time cost: 0.20205283165
inference time cost: 0.205033063889
inference time cost: 0.204127073288
inference time cost: 0.207630157471
inference time cost: 0.20238494873
inference time cost: 0.208182096481
inference time cost: 0.20651102066
inference time cost: 0.211131095886
inference time cost: 0.230016946793
inference time cost: 0.23125910759
inference time cost: 0.210608005524
inference time cost: 0.226739883423
inference time cost: 0.211547851562
inference time cost: 0.215004920959
inference time cost: 0.212172985077
inference time cost: 0.218910932541
inference time cost: 0.222481966019
inference time cost: 0.22424697876
inference time cost: 0.20408987999
inference time cost: 0.203797101974
inference time cost: 0.210248947144
inference time cost: 0.206460952759
inference time cost: 0.205123901367
inference time cost: 0.216490030289
inference time cost: 0.209151983261
inference time cost: 0.205590963364
inference time cost: 0.204297065735
inference time cost: 0.206486940384
inference time cost: 0.210094928741
inference time cost: 0.249784946442
inference time cost: 0.243538856506
inference time cost: 0.25429391861
inference time cost: 0.252223968506
inference time cost: 0.245093822479
inference time cost: 0.245849847794
inference time cost: 0.24328494072
inference time cost: 0.244653940201
inference time cost: 0.233381032944
inference time cost: 0.227144956589
inference time cost: 0.224055051804
inference time cost: 0.213668107986
inference time cost: 0.227074861526
inference time cost: 0.229698181152
inference time cost: 0.219811201096
inference time cost: 0.227994203568
inference time cost: 0.229337930679
inference time cost: 0.217545986176
inference time cost: 0.212108850479
inference time cost: 0.215633153915
inference time cost: 0.213683128357
inference time cost: 0.215692996979
inference time cost: 0.212095975876
inference time cost: 0.208844184875
inference time cost: 0.225620985031
inference time cost: 0.21475982666
inference time cost: 0.207314014435
inference time cost: 0.201117038727
inference time cost: 0.2066218853
inference time cost: 0.214157819748
inference time cost: 0.21735906601
inference time cost: 0.239096879959
inference time cost: 0.219373941422
inference time cost: 0.23636007309
inference time cost: 0.217071056366
inference time cost: 0.214187145233
inference time cost: 0.211740016937
inference time cost: 0.218811988831
inference time cost: 0.217324972153
inference time cost: 0.22531414032
inference time cost: 0.280341863632
inference time cost: 0.279320001602
inference time cost: 0.279906988144
inference time cost: 0.274515151978
inference time cost: 0.278496026993
inference time cost: 0.274595975876
inference time cost: 0.279932022095
inference time cost: 0.282446146011
inference time cost: 0.274383068085
inference time cost: 0.211535930634
inference time cost: 0.209697008133
inference time cost: 0.211524963379
inference time cost: 0.213562011719
inference time cost: 0.222071170807
inference time cost: 0.215301990509
inference time cost: 0.214210033417
inference time cost: 0.216985940933
inference time cost: 0.220325946808
inference time cost: 0.220213890076
inference time cost: 0.221009016037
inference time cost: 0.218371868134
inference time cost: 0.218873977661
inference time cost: 0.218907833099
inference time cost: 0.218776941299
inference time cost: 0.220093011856
inference time cost: 0.219805002213
inference time cost: 0.219503879547
inference time cost: 0.208733081818
inference time cost: 0.202378034592
inference time cost: 0.20908498764
inference time cost: 0.20393204689
inference time cost: 0.205993890762
inference time cost: 0.203629016876
inference time cost: 0.206456899643
inference time cost: 0.209307909012
inference time cost: 0.205091953278
inference time cost: 0.20378613472
inference time cost: 0.205709934235
inference time cost: 0.206635951996
inference time cost: 0.207864999771
inference time cost: 0.205020189285
inference time cost: 0.211507081985
inference time cost: 0.208268165588
inference time cost: 0.205940008163
inference time cost: 0.208065986633
inference time cost: 0.209594964981
inference time cost: 0.210551023483
inference time cost: 0.211791992188
inference time cost: 0.210172176361
inference time cost: 0.208184957504
inference time cost: 0.207793951035
inference time cost: 0.208848953247
inference time cost: 0.204702138901
inference time cost: 0.208296060562
inference time cost: 0.209919929504
inference time cost: 0.208660125732
inference time cost: 0.210602998734
inference time cost: 0.21485209465
inference time cost: 0.213048934937
inference time cost: 0.218766927719
inference time cost: 0.233155965805
inference time cost: 0.306179046631
inference time cost: 0.242048978806
inference time cost: 0.253768920898
inference time cost: 0.248286962509
inference time cost: 0.271131038666
inference time cost: 0.270462989807
inference time cost: 0.25683093071
inference time cost: 0.272734880447
inference time cost: 0.284898042679
inference time cost: 0.254412174225
inference time cost: 0.270535945892
inference time cost: 0.284423112869
inference time cost: 0.267477035522
inference time cost: 0.260974884033
inference time cost: 0.259536027908
inference time cost: 0.263549089432
inference time cost: 0.262032032013
inference time cost: 0.260672092438
inference time cost: 0.266345024109
inference time cost: 0.257710933685
inference time cost: 0.26468706131
inference time cost: 0.262835025787
inference time cost: 0.26095199585
inference time cost: 0.261209964752
inference time cost: 0.258512973785
inference time cost: 0.261729955673
inference time cost: 0.262486934662
inference time cost: 0.262018203735
inference time cost: 0.269473075867
inference time cost: 0.27542591095
inference time cost: 0.269252061844
inference time cost: 0.271088838577
inference time cost: 0.280863046646
inference time cost: 0.269818067551
inference time cost: 0.277490854263
inference time cost: 0.269759893417
inference time cost: 0.278939008713
inference time cost: 0.277776956558
inference time cost: 0.2674908638
inference time cost: 0.277341127396
inference time cost: 0.288149118423
inference time cost: 0.272877931595
inference time cost: 0.274698972702
inference time cost: 0.273131132126
inference time cost: 0.271548986435
inference time cost: 0.27236199379
inference time cost: 0.270072937012
inference time cost: 0.274460077286
inference time cost: 0.269582986832
inference time cost: 0.276633024216
inference time cost: 0.277897119522
inference time cost: 0.277441978455
inference time cost: 0.278612852097
inference time cost: 0.277055025101
inference time cost: 0.27055811882
inference time cost: 0.277670860291
inference time cost: 0.269835948944
inference time cost: 0.281900882721
inference time cost: 0.275520086288
inference time cost: 0.272112846375
inference time cost: 0.271873950958
inference time cost: 0.275208950043
inference time cost: 0.270714998245
inference time cost: 0.249088048935
inference time cost: 0.244168043137
inference time cost: 0.24885392189
inference time cost: 0.241423845291
inference time cost: 0.248044967651
inference time cost: 0.254505872726
inference time cost: 0.244158983231
inference time cost: 0.251082897186
inference time cost: 0.241224050522
inference time cost: 0.242599010468
inference time cost: 0.24365401268
inference time cost: 0.247319936752
inference time cost: 0.247543096542
inference time cost: 0.248133897781
inference time cost: 0.240698814392
inference time cost: 0.241225004196
inference time cost: 0.248049020767
inference time cost: 0.248456954956
inference time cost: 0.24573802948
inference time cost: 0.245584011078
inference time cost: 0.247354984283
inference time cost: 0.243114948273
inference time cost: 0.248263120651
inference time cost: 0.242746829987
inference time cost: 0.248802900314
inference time cost: 0.243211984634
inference time cost: 0.250336885452
inference time cost: 0.248804092407
inference time cost: 0.24892616272
inference time cost: 0.250190019608
inference time cost: 0.242742061615
inference time cost: 0.248377084732
inference time cost: 0.243380069733
inference time cost: 0.246010065079
inference time cost: 0.249619007111
inference time cost: 0.249279022217
inference time cost: 0.246186971664
inference time cost: 0.248100996017
inference time cost: 0.247294902802
inference time cost: 0.252123832703
inference time cost: 0.248955011368
inference time cost: 0.245960950851
inference time cost: 0.247789144516
inference time cost: 0.248814821243
inference time cost: 0.248847007751
inference time cost: 0.243139982224
inference time cost: 0.241555929184
inference time cost: 0.248006105423
inference time cost: 0.244719982147
inference time cost: 0.249027967453
inference time cost: 0.246644020081
inference time cost: 0.242850065231
inference time cost: 0.244970083237
inference time cost: 0.250116825104
inference time cost: 0.240103960037
inference time cost: 0.240646123886
inference time cost: 0.248036146164
inference time cost: 0.249511957169
inference time cost: 0.243547916412
inference time cost: 0.241662979126
inference time cost: 0.250388860703
inference time cost: 0.242209911346
inference time cost: 0.255487918854
inference time cost: 0.253228902817
inference time cost: 0.249907016754
inference time cost: 0.245906114578
inference time cost: 0.250648021698
inference time cost: 0.243247032166
inference time cost: 0.245744943619
inference time cost: 0.248219013214
inference time cost: 0.238717794418
inference time cost: 0.248986005783
inference time cost: 0.247745037079
inference time cost: 0.250778913498
inference time cost: 0.247437000275
inference time cost: 0.243986129761
inference time cost: 0.24107503891
inference time cost: 0.243803024292
inference time cost: 0.249688148499
inference time cost: 0.246629953384
inference time cost: 0.24747800827
inference time cost: 0.249664068222
inference time cost: 0.248086929321
inference time cost: 0.247761964798
inference time cost: 0.25776720047
inference time cost: 0.24661898613
inference time cost: 0.241526842117
inference time cost: 0.246001958847
inference time cost: 0.24324297905
inference time cost: 0.247370004654
inference time cost: 0.249162197113
inference time cost: 0.241807937622
inference time cost: 0.244575023651
inference time cost: 0.242347002029
inference time cost: 0.247106075287
inference time cost: 0.25005197525
inference time cost: 0.243155002594
inference time cost: 0.246999025345
inference time cost: 0.250269889832
inference time cost: 0.242332935333
inference time cost: 0.248075962067
inference time cost: 0.246267080307
inference time cost: 0.244854927063
inference time cost: 0.243191957474
inference time cost: 0.250638961792
inference time cost: 0.248178958893
inference time cost: 0.242247104645
inference time cost: 0.2445499897
inference time cost: 0.243799209595
inference time cost: 0.245778083801
inference time cost: 0.247901916504
inference time cost: 0.247987031937
inference time cost: 0.249349117279
inference time cost: 0.245792865753
inference time cost: 0.243059158325
inference time cost: 0.251693964005
inference time cost: 0.24273109436
inference time cost: 0.247684001923
inference time cost: 0.249033927917
inference time cost: 0.249193906784
inference time cost: 0.248933076859
inference time cost: 0.240727901459
inference time cost: 0.242040157318
inference time cost: 0.243910074234
inference time cost: 0.248558044434
inference time cost: 0.248029947281
inference time cost: 0.259281873703
inference time cost: 0.249243021011
inference time cost: 0.244272947311
inference time cost: 0.244670152664
inference time cost: 0.247740983963
inference time cost: 0.248981952667
inference time cost: 0.243573904037
inference time cost: 0.245356798172
inference time cost: 0.24452996254
inference time cost: 0.243452072144
inference time cost: 0.240988016129
inference time cost: 0.238821983337
inference time cost: 0.24883389473
inference time cost: 0.241976976395
inference time cost: 0.241474866867
inference time cost: 0.242697954178
inference time cost: 0.239205121994
inference time cost: 0.245494127274
inference time cost: 0.241542100906
inference time cost: 0.247225046158
inference time cost: 0.246723890305
inference time cost: 0.244396924973
inference time cost: 0.243910074234
inference time cost: 0.247702121735
inference time cost: 0.243394136429
inference time cost: 0.244313001633
inference time cost: 0.241513967514
inference time cost: 0.249053955078
`
Kindly suggest. Thanks!

**Comment by mashrin** [comment]
on changing line 46 of inference_video_face.py:
`out = cv2.VideoWriter("./media/test_out.avi", cv2.VideoWriter_fourcc('M','J','P','G'), 30.0, (1280, 720))
`
Now a output file is being created but it is blank (just 4 KB file)
The codec for the input video is VP8 but if I change it to:  cv2.VideoWriter_fourcc('V','P','8','0') the output video file is not even getting created.

![image](https://user-images.githubusercontent.com/16867806/34443873-1fcf2584-ecf0-11e7-8fa8-f5730cd429ad.png)

**Comment by mashrin** [comment]
This is now solved.
If someone gets stuck with this later, this is what I did:

I modified line 46
out = cv2.VideoWriter("./media/test_out.avi", 0, 25.0, (1920, 1080))
to-
out = cv2.VideoWriter("./media/test_out.avi",cv.CV_FOURCC('V','P','8','0'), 30.0, (1280, 720))

//Kindly use your own codec (like VP8 in my case) and also modify the frame rate and video dimension.

Plus, don't forget to install the Tensorflow object detection API:
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md

**Comment by yeephycho** [comment]
Closed~
