### ISSUE TITLE
How to return the face detection in json Format

### ISSUE THREAD

**Issue by vnkrish90** [yeephycho/tensorflow-face-detection#8]
Hey, I found Your Code Useful. How do we can use this to make the face co-ordinates like xmin,xmax,ymin,ymax and persons in JSON formatted data

**Comment by yeephycho** [comment]
Thank you @vnkrish90 , 
If you want to save the detection result as JSON, you will have to hack the source code. It won't be hard. View the source code around the drawing rectangle API.
Since this feature has no relationship with the core algorithm, so I will close it.

With regards!

Yeephycho
